basePath: /
host: localhost:3000
info:
  contact:
    email: jorge.duarte@example.com
    name: Jorge Duarte
  description: API for user management
  license:
    name: MIT
  title: User API
  version: "1.0"
paths: {}
swagger: "2.0"
